plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.140'
}

version = "0.0.0"
group = "admsgenter"
base.archivesName = "Convenient Equivalent-1.21.1"
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = "21.1.221"

    parchment {
        minecraftVersion = "1.21"
        mappingsVersion = "2024.07.07"
    }

    runs {
        client { client() }

        server { server() }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            jvmArgument '-Dmixin.env.disableRefMap=true'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "convenient_equivalent" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    maven { url "https://cursemaven.com" }
    maven { url "https://maven.blamejared.com/" }
}

dependencies {
    compileOnly "mezz.jei:jei-1.21.1-common-api:19.27.0.340"
    runtimeOnly "mezz.jei:jei-1.21.1-neoforge:19.27.0.340"
    implementation "curse.maven:convenient-storage-1309336:8878182"
    implementation "curse.maven:projecte-226410:6611984"
}

tasks.register("devJar", Jar) {
    archiveClassifier = "dev"
    from(sourceSets.main.java)
}