modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
[[mods]]
modId = "convenient_equivalent"
version = "0.0.0"
displayName = "Convenient Equivalent"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/convenient-equivalent"
authors = "Admsgenter"
description = '''ProjectE integration with Convenient Storage.'''
[[mixins]]
config = "convenient_equivalent.mixins.json"
[[dependencies."convenient_equivalent"]]
modId = "convenient_storage"
type = "required"
versionRange = "[0.1.2,)"
[[dependencies."convenient_equivalent"]]
modId = "projecte"
type = "required"
versionRange = "*"